<?xml version="1.0" encoding="utf-8"?><Database Name="FitLife" Class="FitlifeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=FitLife;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="AccesoDatos.Properties.Settings" SettingsPropertyName="FitLifeConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="UsuarioID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GimnasioID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ContrasennaHash" Type="System.Data.Linq.Binary" DbType="VarBinary(256) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Rol" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FechaRegistro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_RegistrarUsuario" Method="SP_RegistrarUsuario">
    <Parameter Name="GimnasioID" Parameter="gimnasioID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Apellidos" Parameter="apellidos" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="PasswordHash" Parameter="passwordHash" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Rol" Parameter="rol" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="LlaveCifrado" Parameter="llaveCifrado" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="CodigoVerificacion" Parameter="codigoVerificacion" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="UsuarioID" Parameter="usuarioID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorID" Parameter="errorID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ErrorMsg" Parameter="errorMsg" Type="System.String" DbType="NVarChar(500)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>